
version: 0.2

phases:
  install:
    commands:
      - echo command
    finally:
      - echo command-finally
  pre_build:
    commands:
      - echo pre_build
    finally:
      - echo pre_build-finally
  build:
    commands:
      - echo build
    finally:
      - echo build-finally
  post_build:
    commands:
      - echo post_build
    finally:
      - echo post_build-finally  
artifacts:
  files:
    - '**/*'
    - imageDetail.json
